# Generated by Django 2.2.4 on 2019-09-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bstore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='u_table',
            name='img',
            field=models.ImageField(default=0, upload_to='pics'),
            preserve_default=False,
        ),
    ]
